services:
  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartfinance-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
      - NEXT_PUBLIC_SIGNALR_URL=http://localhost:5000/financehub
      - NEXT_PUBLIC_PAYMENT_SERVICE_URL=http://localhost:3001
    ports:
      - "3000:3000"
    networks:
      - smartfinance-network
    restart: unless-stopped

  # Backend .NET
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartfinance-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=smartfinance.db
      - Jwt__SecretKey=ProductionJWTSecretKey2024_MustBe32CharsLong!
      - Jwt__Issuer=SmartFinance
      - Jwt__Audience=SmartFinanceUsers
    ports:
      - "5000:5000"
    networks:
      - smartfinance-network
    restart: unless-stopped

  # Payment Service Node.js
  payment-service:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    container_name: smartfinance-payment-service
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=ProductionJWTSecretKey2024_MustBe32CharsLong!
      - MAIN_API_URL=http://backend:5000/api/v1
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - smartfinance-network
    restart: unless-stopped

networks:
  smartfinance-network:
    driver: bridge